### PR TITLE
Abhishek Kumar et al.'s CEC 2022 Problem Definitions

### PR DESCRIPTION
**Pull request by dimitri-rusin**
We are integrating functions from the CEC 2022 conference.

This is the paper:

Kumar, Abhishek; Price, Kenneth V.; Mohamed, Ali Wagdy; Hadi, Anas A.; Suganthan, P. N. "Problem Definitions and Evaluation Criteria for the CEC 2022 Special Session and Competition on Single Objective Bound Constrained Numerical Optimization." Technical Report, December 2021.

This repo has some code and the paper's PDF: https://github.com/P-N-Suganthan/2022-SO-BO

We have:

- the actual CEC 2022 functions code,
- and CEC 2022 transformation parameters, in text files,
- Python bindings for the CEC 2022 functions,
- test runs for the CEC 2022 functions.

Let me know, if workflow scripts or something else should be removed or added.

Thank you!

### CODE REVIEW

**Comment by dimitri-rusin** [comment]
This pull request DOES NOT use code from the following repo: https://github.com/ewarchul/cec

Although, it probably should. This is an idea for improvement. That code looks very nice and ordered. And probably contains fewer mistakes than the code committed via this pull request. Although, that code is C code, rather than proper C++ code.

But the code from https://github.com/ewarchul/cec actually does not contain CEC 2022 functions, only functions from CEC 2014, 2015, 2017, 2019, 2021.

They also have R code: https://github.com/ewarchul/cecs

**Comment by dimitri-rusin** [comment]
The factory redefinition at tests/cpp/problem/test_cec_problem.cpp will be removed.

**Review by jacobdenobel — APPROVED** [review]

**Comment by yangyongkang2000** [comment]
> This pull request DOES NOT use code from the following repo: https://github.com/ewarchul/cec
> 
> 
> 
> Although, it probably should. This is an idea for improvement. That code looks very nice and ordered. And probably contains fewer mistakes than the code committed via this pull request. Although, that code is C code, rather than proper C++ code.
> 
> 
> 
> But the code from https://github.com/ewarchul/cec actually does not contain CEC 2022 functions, only functions from CEC 2014, 2015, 2017, 2019, 2021.
> 
> 
> 
> They also have R code: https://github.com/ewarchul/cecs


https://github.com/yangyongkang2000/SEvoBench/blob/main/include/SEvoBench/cec2022.hpp

**Comment by jacobdenobel** [comment]
> > This pull request DOES NOT use code from the following repo: https://github.com/ewarchul/cec
> > Although, it probably should. This is an idea for improvement. That code looks very nice and ordered. And probably contains fewer mistakes than the code committed via this pull request. Although, that code is C code, rather than proper C++ code.
> > But the code from https://github.com/ewarchul/cec actually does not contain CEC 2022 functions, only functions from CEC 2014, 2015, 2017, 2019, 2021.
> > They also have R code: https://github.com/ewarchul/cecs
> 
> https://github.com/yangyongkang2000/SEvoBench/blob/main/include/SEvoBench/cec2022.hpp

Thank you for pointing out the repo. Since indeed we the code in C, we have opted to rewrite the code to C++ and rename some things to make it a bit more sematic. You mention mistakes, but could you point us to any specifics here? As we feel the the code performs correct, this would help us. Thank you.

**Pull request merged**
