### PR TITLE
Adding submodular optimization problems

### PR DESCRIPTION
**Pull request by DV-Anh**
Problem Name(s):

1. Max Coverage
2. Max Cut
3. Max Influence
4. Packing While Travelling

Added file(s):

1. graph_problem.hpp
2. max_coverage.hpp
3. max_cut.hpp
4. max_influence.hpp
5. pack_while_travel.hpp
6. run_submodular_instances.cpp

Definition(s) of the problem(s):

1. Max Coverage: given a graph G=(V,E), a vertex weight function w, constraint weight function c, find a subset X of V maximizing Cover(X) s.t. c(X)<=B for some bound B, where Cover(X) is the weight sum of vertices in X and adjacent to X, and c(X) is the constraint weight sum of vertices in X. In case of directed graph, Cover(X) only counts, among the adjacent vertices, the ones on the in-coming end.
2. Max Cut: given a graph G=(V,E), an edge weight function w, constraint weight function c, find a subset X of V maximizing Cut(X) s.t. c(X)<=B for some bound B, where Cut(X) is the weight sum of edges coming out of X minus the weight sum of edges coming into X, and c(X) is the constraint weight sum of vertices in X. In case of undirected graph, all edges are considered out-going edges.
3. Max Influence: given a graph G=(V,E), a vertex weight function w, constraint weight function c, find a subset X of V maximizing N(X) s.t. c(X)<=B for some bound B, where N(X) is the expected weight sum of activated vertices propagated from X along out-going edges with edge weight being propagation probability, and c(X) is the constraint weight sum of vertices in X. In case of directed graph, propagation goes both ways with the same probability.
4. Packing While Travelling: given a cyclic route going through locations, with distances between locations, maximum and minimum travel velocity, a set of items in each location each with a profit and a weight, maximize f(X) s.t. c(X)<=B for some bound B, where X is the picked items at all location, f(X) is the profit sum minus total travel time calculated by distances, velocities and current weights during the travel, and c(X) is the constraint weight sum of items in X.

Description of the implementation:

graph_problem.hpp contains Graph class and GraphInstance class, which includes necessary data to define a graph problem, and reads graph data from files. max_coverage.hpp, max_cut.hpp, max_influence.hpp, pack_while_travel.hpp include definitions of concrete problem classes subclassing Graph (except pack_while_travel) and implementing evaluation functions. Their constructors derive the problem instance dimension from the associated GraphInstance object. File run_submodular_instances.cpp include how these problems can be run in an experiment.

Additional information:

More details on the problems are included in the Evolutionary Submodular Optimization Competition website (to be updated): [https://cs.adelaide.edu.au/~optlog/CompetitionESO2022.php](url)

### CODE REVIEW

**Comment by FurongYe** [comment]
Thanks for the pull request!  Before merging, could you please solve the following issues? 

- An error occurs while testing on MacOS. Please see the output below.

    ......
    [ 12%] Building CXX object tests/CMakeFiles/test_eaf.dir/cpp/entrypoint.cpp.o
    [ 13%] Linking CXX executable test_eaf
    libc++abi: terminating with uncaught exception of type std::invalid_argument: stod: no conversion
    CMake Error at /usr/local/lib/python3.8/site-packages/cmake-3.18.4.post1-py3.8-macosx-10.15-x86_64.egg/cmake/data/CMake.app/Contents/share/cmake-3.18/Modules/GoogleTestAddTests.cmake:77 (message):
    Error running test executable.

    Path: '/Users/fye/Codes/Git/subModularOptimization/DV/IOHexperimenter/tests/test_eaf'
    Result: Child aborted
    Output:


    Call Stack (most recent call first):
      /usr/local/lib/python3.8/site-packages/cmake-3.18.4.post1-py3.8-macosx-10.15-x86_64.egg/cmake/data/CMake.app/Contents/share/cmake-3.18/Modules/GoogleTestAddTests.cmake:173 (gtest_discover_tests_impl)

- Please follow the code check (https://app.codacy.com/gh/IOHprofiler/IOHexperimenter/pullRequest?prid=9146069).

- The hyperlink of the site https://gecco-2022.sigevo.org/Competitions in PR seems wrong.

**Comment by FurongYe** [comment]
Thanks for the pull request!  Before merging, could you please solve the following issues? 

- An error occurs while testing on MacOS. Please see the output below.

    ......
    [ 12%] Building CXX object tests/CMakeFiles/test_eaf.dir/cpp/entrypoint.cpp.o
    [ 13%] Linking CXX executable test_eaf
    libc++abi: terminating with uncaught exception of type std::invalid_argument: stod: no conversion
    CMake Error at /usr/local/lib/python3.8/site-packages/cmake-3.18.4.post1-py3.8-macosx-10.15-x86_64.egg/cmake/data/CMake.app/Contents/share/cmake-3.18/Modules/GoogleTestAddTests.cmake:77 (message):
    Error running test executable.

    Path: '/Users/fye/Codes/Git/subModularOptimization/DV/IOHexperimenter/tests/test_eaf'
    Result: Child aborted
    Output:


    Call Stack (most recent call first):
      /usr/local/lib/python3.8/site-packages/cmake-3.18.4.post1-py3.8-macosx-10.15-x86_64.egg/cmake/data/CMake.app/Contents/share/cmake-3.18/Modules/GoogleTestAddTests.cmake:173 (gtest_discover_tests_impl)

- Please follow the code check (https://app.codacy.com/gh/IOHprofiler/IOHexperimenter/pullRequest?prid=9146069).

- The hyperlink of the site https://gecco-2022.sigevo.org/Competitions in PR seems wrong.

**Comment by DV-Anh** [comment]
Thanks for the feedback. The segfault should be fixed now. Please let me know if the error persists.

**Comment by FurongYe** [comment]
> Thanks for the feedback. The segfault should be fixed now. Please let me know if the error persists.

Thanks for the update. However, an error occurs on both Linux and macOS systems.

    terminate called after throwing an instance of 'std::invalid_argument'
    what():  stod

**Comment by DV-Anh** [comment]
> Thanks for the update. However, an error occurs on both Linux and macOS systems.
> 
> ```
> terminate called after throwing an instance of 'std::invalid_argument'
> what():  stod
> ```
Everything ran fine on Windows, though. For now, changing all instance files' eol to Unix standard should fix this.

**Comment by FurongYe** [comment]
> > Thanks for the update. However, an error occurs on both Linux and macOS systems.
> > ```
> > terminate called after throwing an instance of 'std::invalid_argument'
> > what():  stod
> > ```
> 
> Everything ran fine on Windows, though. For now, changing all instance files' eol to Unix standard should fix this.

Thanks! Now the project can be compiled successfully.

One last issue (hopefully), at line https://github.com/DV-Anh/IOHexperimenter/blob/23b1001b45dc6386dd5a5874322f3e31272f1479/include/ioh/problem/submodular/pack_while_travel.hpp#L202 . Will read_instance_by_id(instance - 1, instance_list_file) always be identical to get_dim()? I occasionally get seg fault error, which may be caused there.

**Comment by DV-Anh** [comment]
> Thanks! Now the project can be compiled successfully.
> 
> One last issue (hopefully), at line https://github.com/DV-Anh/IOHexperimenter/blob/23b1001b45dc6386dd5a5874322f3e31272f1479/include/ioh/problem/submodular/pack_while_travel.hpp#L202 . Will read_instance_by_id(instance - 1, instance_list_file) always be identical to get_dim()? I occasionally get seg fault error, which may be caused there.

Thanks for confirming this! I was wondering whether that bit is going to cause issues. The assumption is that `read_instance_by_id` is called before `get_dim`, but there's no guarantee which order the arguments are evaluated in. They are evaluated in the desired order on my system, but apparently it doesn't reliably do so on others. I'll update the constructor to be less error-prone.

**Review by FurongYe — APPROVED** [review]

**Pull request merged**
